apiVersion: apps/v1
kind: Deployment
metadata:
  name: incidentmg
  namespace: default
  labels:
    app: incidentmg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incidentmg
  template:
    metadata:
      labels:
        app: incidentmg
    spec:
      containers:
      - image: noimage:v0.0.0 # we'll use localization later to correctly specify the image
        name: incidentmg
        ports:
        - containerPort: 9898
          name: http
