apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: incidentmg
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  targetNamespace: default
  sourceRef:
    kind: OCIRepository
    name: incidentmg-deployment-localized
  path: ./
